### ISSUE TITLE
EKS - PLEG is not healthy

### ISSUE THREAD

**Issue by EinavDanielDX** [awslabs/amazon-eks-ami#837] opened 2022-01-11 09:11 UTC
**What happened**:
Random nodes in cluster are flapping between NodeReady and NodeNotReady state, with message "PLEG is not healthy", results in pods being terminated and not rescheduled

**What you expected to happen**:
Node state should be ready all the time

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): t3a.2xlarge
- EKS Platform version: eks.2
- Kubernetes version: 1.21
- AMI Version: amazon-eks-node-1.21-v20211206 (latest)
- Kernel: 5.4.156-83.273.amzn2.x86_64
- Container Runtime Version:  docker://20.10.7 (default)
- Kubelet Version: v1.21.5-eks-bc4871b

**Comment by sgblv** [comment] 2022-03-07 06:24
Hi! I've faced with exactly same issue. Did you manage it to fix somehow?

**Comment by pichouk** [comment] 2022-03-11 09:14
Hi @EinavDanielDX I have the same issue in my EKS cluster with almost the same setup (I just have an AMI version older than yours). What was yoru `vpc-cni` addon versions ?
I'm running with `v1.10.1-eksbuild.1` which is compatible with a 1.21 cluster. I'll try to upgrade to `v1.10.2-eksbuild.1` but the `vpc-cni` changelog doesn't seems to fix an issue that might be related with PLEG.

**Comment by EinavDanielDX** [comment] 2022-03-13 08:00
We are currently using ` v1.10.1-eksbuild.1` CNI version.
In our case we had to replace our nodes **after** we updated the CNI version. Updating CNI and not replacing nodes did took no effect.

**Comment by sedflix** [comment] 2022-03-30 10:18
I'm facing the same issue. 

- PLEG duration usually goes high on a node
- We observed that this issue happens only on nodes that have a large number of short-lived pods(ephemeral workloads) for a prolonged period. (~200 pods on 4xlarge )
- We tried to create a new node group for ephemeral workload with smaller instances to limit the number of pods that can be scheduled on a node. We went with 2x large instance. It allowed us only to schedule around 60 pods per node. This didn’t solve the issue.
- We observe “xtable locks” in the logs of calico-node and kube-proxy pods on that node.

AMI Description:
- EKS Kubernetes Worker AMI with AmazonLinux2 image, (k8s: 1.21.5, docker: 20.10.7-5.amzn2, containerd: 1.4.6-8.amzn2) 
- amazon/amazon-eks-node-1.21-v20220309

**Comment by khushboo121** [comment] 2022-11-11 05:44
WE are facing this issue with EKS 1.22

**Comment by asahnovskiy-deloitte** [comment] 2022-11-24 09:24
We are facing this issue with EKS 1.23 and new vpc cni addon amazon-k8s-cni-init:v1.11.4 
But I see the issue only on Spot nodes

**Comment by cartermckinnon** [comment] 2022-12-01 23:31
This is a very generic error; it means that Kubelet isn't able to reconcile it's desired topology with the actual state of the running containers. It can happen for many reasons, most recently we saw this caused by a problematic kernel patch, see #1071 . I'm going to close this issue, as the environment reported in the original description is superseded by new kubelet and docker versions. Please open new issues detailing your environments if this issue continues.

**Closed by cartermckinnon** 2022-12-01 23:31 UTC
