### ISSUE TITLE
Cannot start container after uptime of 7-8 hours

### ISSUE THREAD

**Issue by dirkoberhaus** [awslabs/amazon-eks-ami#1278] opened 2023-04-25 11:04 UTC
**What happened**:
We build our own EKS AMI Based on this release https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230411 and updates our cluster every day. After this release we see problems creating container on some nodes after an uptime of 7-8h

**What you expected to happen**:
The nodes should be able to start container

**How to reproduce it (as minimally and precisely as possible)**:
Create a EKS cluster in version 1.24 with eksctl and an AMI bases on this release: https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230411
Wait 7-8h (perhaps this depends on cluster usage)
After this time the nodes cannot start any container. The nodes looks healthy via AWS console or kubectl.

We switched back to this version https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230406 and the problems disapeared.

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-central-1
- Instance Type(s): m6i.2xlarge
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.4"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): "1.24"
- AMI Version: https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230411
- Kernel (e.g. `uname -a`): 'Currently we have no access to the nodes via ssh'
- Release information (run `cat /etc/eks/release` on a node): 'Currently we have no access to the nodes via ssh'

```
```

Currently I will prepare a cluster with ssh access to get more information.

Did anyone also experience the same problems?

**Comment by cartermckinnon** [comment] 2023-04-25 16:34
@dirkoberhaus do you happen to be using seccomp? https://github.com/awslabs/amazon-eks-ami/issues/1219

You can also use SSM to access the node if you don't have SSH configured.

**Comment by alexku7** [comment] 2023-04-25 16:51
Exactly the same issue with that AMI version. 
20230411 seems to be broken

**Comment by alexku7** [comment] 2023-04-25 17:08
> @alexku7 are you also using the Kubernetes 1.24 AMI?

Nope. But i confirm the same issue on 1.25 and 1.26 versions.

We reverted to the v20230406 version which works good.
The problem is as described here https://github.com/awslabs/amazon-eks-ami/issues/1219

The `cat /proc/vmallocinfo | grep bpf_jit | awk '{s+=$2} END {print s}'` shows very high number  exceeding the limit.

**Comment by cartermckinnon** [comment] 2023-04-25 18:10
Okay, just confirming this is the same issue as #1219.

@dirkoberhaus please let me know if you're experiencing the same issue.

**Comment by dirkoberhaus** [comment] 2023-04-25 22:24
> seccomp

Yes, we install own PSPs which are annotated with 

 seccomp.security.alpha.kubernetes.io/allowedProfileNames ....
 
 I'll try to reproduce this error and check if I can see the same mentioned by @alexku7

**Comment by cartermckinnon** [comment] 2023-04-25 22:34
Okay, gotcha. I'm going to close this as a duplicate of #1219, please follow that thread for updates 👍 .

**Closed by cartermckinnon** 2023-04-25 22:34 UTC
