### ISSUE TITLE
Change in kubelet location?

### ISSUE THREAD

**Issue by caphrim007** [awslabs/amazon-eks-ami#638] opened 2021-03-19 01:46 UTC
**What happened**:

Running a build of 1.19 and 1.18, I receive an error about a 301 redirect in the install-worker.sh script.

```
$ wget https://amazon-eks.s3.us-east-1.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubelet
--2021-03-18 18:43:46--  https://amazon-eks.s3.us-east-1.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubelet
Resolving amazon-eks.s3.us-east-1.amazonaws.com (amazon-eks.s3.us-east-1.amazonaws.com)... 52.217.64.224
Connecting to amazon-eks.s3.us-east-1.amazonaws.com (amazon-eks.s3.us-east-1.amazonaws.com)|52.217.64.224|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: unspecified
ERROR: Redirection (301) without location.
```

**What you expected to happen**:

install-worker.sh would succeed

**How to reproduce it (as minimally and precisely as possible)**:

I am, personally, seeing this on the plain copy of the install-worker.sh script. I don't know if its been like this for a while since I build new images roughly every 2 weeks, and haven't changed any configuration on my end.

**Anything else we need to know?**:

**Environment**:
- AWS Region:
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

visiting the link directly, S3 returns this

```
<Error>
<Code>PermanentRedirect</Code>
<Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message>
<Endpoint>amazon-eks.s3-us-west-2.amazonaws.com</Endpoint>
<Bucket>amazon-eks</Bucket>
<RequestId>CSBXD4FECHX57BFW</RequestId>
<HostId>Ec1Oo4YRSwf14COE30LfXnoCC1fNOibhNcpuvdFm//a/yucczxYxHcd/YQeDeZsB+3P70AAxRbM=</HostId>
</Error>
```

wget headers specify no Location to redirect to

```
  HTTP/1.1 301 Moved Permanently
  x-amz-bucket-region: us-west-2
  x-amz-request-id: EWB1MNE5FNGXZT1W
  x-amz-id-2: wQeSmegLDJpIeXV05ZDrL2eZ7XX5wUYXG1S8ThijDwApJ3RIMPg8Ui23QcwMA+FmxXulillbslU=
  Content-Type: application/xml
  Transfer-Encoding: chunked
  Date: Fri, 19 Mar 2021 02:11:03 GMT
  Server: AmazonS3
```

**Comment by mmerkes** [comment] 2021-03-24 16:27
Can you share the specific command that you were running?

**Comment by caphrim007** [comment] 2021-03-24 16:37
@mmerkes I assume it was this

https://github.com/awslabs/amazon-eks-ami/blob/master/scripts/install-worker.sh#L177

I was only running the packer build commands that I normally do. the wget was happening within the scripts found in the repo here.

**Comment by mmerkes** [comment] 2021-03-24 16:59
Ya. I meant the `make` command. For example, I just ran `make `1.18` and commented out [the bit that uses the AWS CLI](https://github.com/awslabs/amazon-eks-ami/blob/master/scripts/install-worker.sh#L171-L175) to make sure it used `wget` and it worked fine for me, using the `https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubelet` URL.

That being said, looks like the issue is that you're not using `us-west-2` as the `BINARY_BUCKET_REGION`. For regular AWS regions, they should use the bucket in `us-west-2`. The override is intended for regions in separate AWS partitions like the China regions.

**Comment by caphrim007** [comment] 2021-03-24 17:05
I think its probably due to the AWS_REGION or AWS_DEFAULT_REGION env vars being forwarded to the packer template file. If those regions are us-east-1, then it shows the error.

Our environments dont usually specify the region, so we just fall back to us-east-1. When I specifically override that region with us-west-2 it works, but i dont remember us-west-2 region being a requirement. I've been building these images since 1.16 and this is the first time I've seen the error.

Is this a new requirement?

**Comment by mmerkes** [comment] 2021-03-24 17:11
AFAIK, no. I don't recall any and don't see any changes to the AMI that would impact this. The binaries are unchanged from January, so there should be no changes to the S3 bucket setup. Perhaps, some change to your environment?

Anyway, sounds like you have it working, so I'm going to close this issue.

**Closed by mmerkes** 2021-03-24 17:11 UTC
