### ISSUE TITLE
Why only kubereserved ?

### ISSUE THREAD

**Issue by kakarotbyte** [awslabs/amazon-eks-ami#880] opened 2022-03-08 16:15 UTC
**What would you like to be added**:
Adding System Reserved to the bootstrap script. 

**Why is this needed**:

Currently kubereserved and eviction threshold are being added to the worker node by default. It will be benificial to add System Reserved  as well.

https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L442-L443

**Comment by stevehipwell** [comment] 2022-03-09 14:13
@kakarotbyte I think the current design takes into account all non pod resource requirements and sets them via kube reserved and eviction. AFAIK the system reserved settings don't necessarily work as expected and add extra complexity, I'm happy to be told otherwise but this is what I found out when I looked into this area. You might be interested in https://github.com/awslabs/amazon-eks-ami/issues/782 which covers why the current defaults probably want overriding and should have some related links.

**Comment by cartermckinnon** [comment] 2022-12-08 02:07
I'm going to close this as a duplicate of #661, but I think I agree with @stevehipwell here. Because reserving additional resources for system daemons would take away resources from user's workloads, we need to review more evidence before making this change.

**Closed as completed by cartermckinnon** 2022-12-08 02:07 UTC
