### ISSUE TITLE
When does EKS support R5?

### ISSUE THREAD

**Issue by chenrui333** [awslabs/amazon-eks-ami#72] opened 2018-10-15 15:20 UTC
When creating the cluster the EKS seems still not supporting R5 type, just want to confirm in here.

![image](https://user-images.githubusercontent.com/1580956/46960338-52437c80-d06c-11e8-989f-2085a9ce257e.png)

**Comment by chenrui333** [comment] 2018-10-15 16:31
I guess this is just because the r5 type is not included into the release `nodegroup.yaml`.
`s3://amazon-eks/cloudformation/2018-08-30/amazon-eks-nodegroup.yaml`

**Comment by micahhausler** [comment] 2018-10-15 17:12
You're correct, we just need to release the latest nodegroup template. We'll be updating it later this week most likely. Closing as duplicate of #47

**Closed by micahhausler** 2018-10-15 17:12 UTC
