### ISSUE TITLE
EKS 1.30 | al2023 Failed to bootstrap

### ISSUE THREAD

**Issue by sebastianserrano** [awslabs/amazon-eks-ami#1834] opened 2024-06-05 08:49 UTC
**What happened**:
`/var/log/cloud-init.log` reports SELinux issues

**What you expected to happen**:
`/var/log/cloud-init.log` to run to completion

**How to reproduce it (as minimally and precisely as possible)**:
Simply run `amazon-eks-node-al2023-x86_64-standard-1.30-v20240531` and check `tail -n 5 /var/log/cloud-init.log`

**Anything else we need to know?**:

**Environment**:
- AWS Region: 
  - `eu-north-1`
- Instance Type(s): 
  - `r5.2xlarge`
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): 
  - `eks.2`
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 
  - `1.30`
- AMI Version:
  - `1.30.0-20240531`
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-0560d643fb0791edd"
BUILD_TIME="Fri May 31 04:57:11 UTC 2024"
BUILD_KERNEL="6.1.91-99.172.amzn2023.x86_64"
ARCH="x86_64"
```

<img width="1410" alt="Screen Shot 2024-06-05 at 10 43 48 AM" src="https://github.com/awslabs/amazon-eks-ami/assets/19766755/4958be45-e320-407a-8172-db88d52c5387">

**Comment by cartermckinnon** [comment] 2024-06-05 18:50
Can you grab the complete `/var/log/cloud-init-output.log`? You can open an AWS Support case if you can't provide the logs here, we'll track it down 👍

**Comment by cartermckinnon** [comment] 2024-06-05 19:16
Closing as duplicate of #1833, please open an AWS Support case.

**Closed by cartermckinnon** 2024-06-05 19:16 UTC
