### ISSUE TITLE
EXTERNAL-IP missing

### ISSUE THREAD

**Issue by emman27** [awslabs/amazon-eks-ami#75] opened 2018-10-17 02:01 UTC
Hi guys, I'm not sure if there's something I'm missing on the `bootstrap.sh` script, or it's just something that EKS doesn't support. My use case involves using `NodePort` based services for setup of the cluster (I'm migrating from GKE), and it seems that the public IP of my EKS worker nodes is not being registered with k8s. Here's a quick summary of my output:

```
kubectl get no -o wide

NAME                                           STATUS   ROLES    AGE   VERSION   EXTERNAL-IP   OS-IMAGE         KERNEL-VERSION                CONTAINER-RUNTIME
ip-10-122-113-212.us-west-2.compute.internal   Ready    <none>   22h   v1.10.3   <none>        Amazon Linux 2   4.14.62-70.117.amzn2.x86_64   docker://17.6.2
```

Going for `-o yaml` confirms that there is no external IP being picked up. However, I've also inspected the actual EC2 instance here and there is in fact a public IP available.

My `userdata.sh` script is also below:

```sh
#!/bin/bash -xe

/etc/eks/bootstrap.sh cluster_name --kubelet-extra-args '--node-labels=something=hello,somethingelse=bye --register-with-taints=taint1=true'
```

Is there something I am missing?

**Comment by micahhausler** [comment] 2018-10-17 02:14
Closing as duplicate of #60, see my comment there

**Closed by micahhausler** 2018-10-17 02:14 UTC
