### ISSUE TITLE
CoreDNS version breaks networking in pods

### ISSUE THREAD

**Issue by 0verc1ocker** [awslabs/amazon-eks-ami#200] opened 2019-02-21 21:52 UTC
**What happened**:

I created two nodegroups. The one that had `--register-with-taints` passed into the --kubelet-extra-args does not have a working docker networking from inside pods.

**What you expected to happen**:

Networking inside a pod on a tainted node should work.

**How to reproduce it (as minimally and precisely as possible)**:

Create a nodegroup with taints and labels.

I am creating two node groups and passing in `--register-with-taints` to the kubelet of one of them. The group that has extra argument to kubelet registers the taints properly but then networking inside of the containers on those nodes stop working. Nothing in the logs for aws-node, kubelet, or the CNI. Everything is fine when this same nodegroup starts up without the kubelet extra argument `--register-with-taints`.

The taint is passed to bootstrap.sh as such:
```
--kubelet-extra-args '--register-with-taints=\"dedicated=jobs:NoSchedule\" --node-labels=testing/role=shared'
```

Using the latest ami for us-east-1 and using `amazon-k8s-cni:v1.3.2` image for aws-node ds.

**Comment by devkid** [comment] 2019-02-21 21:56
Are you running the latest version of the `aws-node` daemonset? Starting with 1.11 it got a toleration for everything: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.3/aws-k8s-cni.yaml#L68 You should probably update the daemonset by applying this manifest.

**Comment by 0verc1ocker** [comment] 2019-02-21 22:05
@devkid Thank you for the reply.

Yes, I upgraded the image and the manifest to the latest for aws-node cni by this exact command:

`kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.3/aws-k8s-cni.yaml`

Same problems persisted, that's why I opened the issues

**Comment by devkid** [comment] 2019-02-21 22:09
Can you give the output of `kubectl -n kube-system get -o yaml daemonset/aws-node` and `kubectl get -o yaml node <node name>`?

**Comment by 0verc1ocker** [comment] 2019-02-21 22:44
Here is the output of `kubectl -n kube-system get -o yaml daemonset/aws-node`:

```
kubectl -n kube-system get -o yaml daemonset/aws-node
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"k8s-app":"aws-node"},"name":"aws-node","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"k8s-app":"aws-node"}},"template":{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":""},"labels":{"k8s-app":"aws-node"}},"spec":{"containers":[{"env":[{"name":"AWS_VPC_K8S_CNI_LOGLEVEL","value":"DEBUG"},{"name":"MY_NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"WATCH_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.3.2","imagePullPolicy":"Always","name":"aws-node","ports":[{"containerPort":61678,"name":"metrics"}],"resources":{"requests":{"cpu":"10m"}},"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/host/opt/cni/bin","name":"cni-bin-dir"},{"mountPath":"/host/etc/cni/net.d","name":"cni-net-dir"},{"mountPath":"/host/var/log","name":"log-dir"},{"mountPath":"/var/run/docker.sock","name":"dockersock"}]}],"hostNetwork":true,"serviceAccountName":"aws-node","tolerations":[{"operator":"Exists"}],"volumes":[{"hostPath":{"path":"/opt/cni/bin"},"name":"cni-bin-dir"},{"hostPath":{"path":"/etc/cni/net.d"},"name":"cni-net-dir"},{"hostPath":{"path":"/var/log"},"name":"log-dir"},{"hostPath":{"path":"/var/run/docker.sock"},"name":"dockersock"}]}},"updateStrategy":{"type":"RollingUpdate"}}}
  creationTimestamp: "2019-02-11T15:03:59Z"
  generation: 2
  labels:
    k8s-app: aws-node
  name: aws-node
  namespace: kube-system
  resourceVersion: "1876382"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/daemonsets/aws-node
  uid: 42a19e32-2e0e-11e9-a7d9-023409a82086
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: aws-node
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        k8s-app: aws-node
    spec:
      containers:
      - env:
        - name: AWS_VPC_K8S_CNI_LOGLEVEL
          value: DEBUG
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.3.2
        imagePullPolicy: Always
        name: aws-node
        ports:
        - containerPort: 61678
          hostPort: 61678
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 10m
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
        - mountPath: /host/var/log
          name: log-dir
        - mountPath: /var/run/docker.sock
          name: dockersock
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: aws-node
      serviceAccountName: aws-node
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /opt/cni/bin
          type: ""
        name: cni-bin-dir
      - hostPath:
          path: /etc/cni/net.d
          type: ""
        name: cni-net-dir
      - hostPath:
          path: /var/log
          type: ""
        name: log-dir
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: dockersock
  templateGeneration: 2
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 4
  desiredNumberScheduled: 4
  numberAvailable: 4
  numberMisscheduled: 0
  numberReady: 4
  observedGeneration: 2
  updatedNumberScheduled: 4
```

And here is the output of a node from the nodegroup that doesn't have working networking for pods:

`kubectl get -o yaml node <node name>`

```
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2019-02-21T22:10:39Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: r4.xlarge
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: us-east-1
    failure-domain.beta.kubernetes.io/zone: us-east-1b
    kubernetes.io/hostname: ip-192-168-177-199.ec2.internal
    testing/role: shared
  taints: dedicated=jobs:NoSchedule
  name: ip-192-168-177-199.ec2.internal
  resourceVersion: "1882249"
  selfLink: /api/v1/nodes/ip-192-168-177-199.ec2.internal
  uid: 85a80a98-3625-11e9-a7d9-023409a82086
spec:
  providerID: aws:///us-east-1b/i-087c43d1d8cd661fd
status:
  addresses:
  - address: 192.168.177.199
    type: InternalIP
  - address: 3.93.49.14
    type: ExternalIP
  - address: ip-192-168-177-199.ec2.internal
    type: InternalDNS
  - address: ec2-3-93-49-14.compute-1.amazonaws.com
    type: ExternalDNS
  - address: ip-192-168-177-199.ec2.internal
    type: Hostname
  allocatable:
    cpu: "4"
    ephemeral-storage: "19316009748"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 31290712Ki
    pods: "58"
  capacity:
    cpu: "4"
    ephemeral-storage: 20959212Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 31393112Ki
    pods: "58"
  conditions:
  - lastHeartbeatTime: "2019-02-21T22:40:23Z"
    lastTransitionTime: "2019-02-21T22:10:39Z"
    message: kubelet has sufficient disk space available
    reason: KubeletHasSufficientDisk
    status: "False"
    type: OutOfDisk
  - lastHeartbeatTime: "2019-02-21T22:40:23Z"
    lastTransitionTime: "2019-02-21T22:10:39Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2019-02-21T22:40:23Z"
    lastTransitionTime: "2019-02-21T22:10:39Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2019-02-21T22:40:23Z"
    lastTransitionTime: "2019-02-21T22:10:39Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2019-02-21T22:40:23Z"
    lastTransitionTime: "2019-02-21T22:10:59Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - colemickens/oauth2_proxy@sha256:2ac6de24b9d06378c04d2ff29c4f9b54168c807774ea19d8268ac82fda0493af
    - colemickens/oauth2_proxy:latest
    sizeBytes: 777921667
  - names:
    - 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni@sha256:33ed8e136cc082af5d48c9756e2a2913e9d84c8ead841e34dc4efcf28a3891a0
    - 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.3.2
    sizeBytes: 367010179
  - names:
    - 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy@sha256:45be43d0609c92aad89cb8607a0452a59db46133cf9fede314367eb16fac5750
    - 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy:v1.11.5
    sizeBytes: 97950829
  - names:
    - k8s.gcr.io/heapster@sha256:3dff9b2425a196aa51df0cebde0f8b427388425ba84568721acf416fa003cd5c
    - k8s.gcr.io/heapster:v1.3.0
    sizeBytes: 68105973
  - names:
    - registry.opensource.zalan.do/teapot/external-dns@sha256:3238aaf10240d6322c87073766f67d8cf24dc2db4f0ef01b62d18890573f8075
    - registry.opensource.zalan.do/teapot/external-dns:v0.5.9
    sizeBytes: 51942746
  - names:
    - k8s.gcr.io/addon-resizer@sha256:dcec9a5c2e20b8df19f3e9eeb87d9054a9e94e71479b935d5cfdbede9ce15895
    - k8s.gcr.io/addon-resizer:1.7
    sizeBytes: 38983736
  - names:
    - prom/node-exporter@sha256:c390c8fea4cd362a28ad5070aedd6515aacdfdffd21de6db42ead05e332be5a9
    - prom/node-exporter:v0.17.0
    sizeBytes: 20982005
  - names:
    - prom/pushgateway@sha256:04d01442ef40796ca7fc97735de8f7b9a87a9a7db8b7e81ca64d5adf44608e92
    - prom/pushgateway:v0.6.0
    sizeBytes: 16527231
  - names:
    - radial/busyboxplus@sha256:a68c05ab1112fd90ad7b14985a48520e9d26dbbe00cb9c09aa79fdc0ef46b372
    - radial/busyboxplus:curl
    sizeBytes: 4233788
  - names:
    - 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause-amd64@sha256:bea77c323c47f7b573355516acf927691182d1333333d1f41b7544012fab7adf
    - 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause-amd64:3.1
    sizeBytes: 742472
  nodeInfo:
    architecture: amd64
    bootID: f0e816fa-69f1-4ca7-afce-4afd56e6755c
    containerRuntimeVersion: docker://18.6.1
    kernelVersion: 4.14.97-90.72.amzn2.x86_64
    kubeProxyVersion: v1.11.5
    kubeletVersion: v1.11.5
    machineID: 6129e0916d4f4273a690f0af146dfe98
    operatingSystem: linux
    osImage: Amazon Linux 2
    systemUUID: EC23D717-2B55-EABC-407B-755811F0524D
```

**Comment by micahhausler** [comment] 2019-02-22 20:23
I can confirm this is an issue. This looks more like a CNI issue than the AMI. 

Closing in favor of aws/amazon-vpc-cni-k8s#328

**Comment by 0verc1ocker** [comment] 2019-02-22 21:03
Thank you for the response @micahhausler . Can we get some urgency on this aws CNI issue?

I have added a detail of all the debugging I tried today but the problem persists:

https://github.com/aws/amazon-vpc-cni-k8s/issues/328#issuecomment-466546234

**Comment by devkid** [comment] 2019-02-23 11:32
@0verc1ocker Would it be an option to use v1.3.0 of the CNI plugin? This works perfectly fine for us at the moment (also with taints and tolerations).

**Comment by 0verc1ocker** [comment] 2019-02-24 04:43
I did some testing tonight and reverted back to 1.3.0 aws_node image 
`602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:1.3.0`

Networking is still broken from within the pods of the tainted nodes. 

```
[ root@curl-test-68555c7c47-4nsh6:/ ]$ curl www.google.com
curl: (6) Couldn't resolve host 'www.google.com'
```

I rebuilt the two nodegroups and still broken. @devkid we are spinning up two nodegroups. Are you only using one nodegroup for your environment? Can you please test with two nodegroups with different taints and labels?

I'm beginning to think this issue is related to having more than one nodegroup. Is something supposed to be changed in the aws_node cni configurations when using two nodegroups on seperate security groups but same subnets?

**Comment by devkid** [comment] 2019-02-24 09:30
@0verc1ocker I just deployed a single nginx pod onto a node running version 1.3.0 of the CNI container and it works for me. Did you delete the `aws-node` pod on the instance on which you were doing your tests after downgrading the image? By default, the `aws-node` daemonset doesn't replace pods on updates.

**Comment by devkid** [comment] 2019-02-24 09:34
@0verc1ocker I just deployed a single nginx pod onto a node running version 1.3.0 of the CNI container and it works for me. Did you delete the `aws-node` pod on the instance on which you were doing your tests after downgrading the image? By default, the `aws-node` daemonset doesn't replace pods on updates.

We are using multiple node groups with different taints and labels and by now didn't experience the issue you describe (at least not up until 1.3.0, we didn't try any newer version yet).

You mention that you use different security groups. Is the instance where the problem occurs allowed to access the instance where core-dns / kube-dns is running? If not, this would explain your resolve errors.

**Comment by 0verc1ocker** [comment] 2019-02-25 00:31
This may be a little far-fetched but in version 1.11.x of K8s there was a new update that prevents nodes from updating their own taints on the API object. Could there be some kind of race condition that may be happening when the nodes are trying to register with the kube-apiserver? Is NodeRestriction enabled on the EKS Control Plane api-server?

https://github.com/kubernetes/kubernetes/pull/63167

**Comment by 0verc1ocker** [comment] 2019-02-25 02:16
> @0verc1ocker I just deployed a single nginx pod onto a node running version 1.3.0 of the CNI container and it works for me. Did you delete the `aws-node` pod on the instance on which you were doing your tests after downgrading the image? By default, the `aws-node` daemonset doesn't replace pods on updates.
> 
> We are using multiple node groups with different taints and labels and by now didn't experience the issue you describe (at least not up until 1.3.0, we didn't try any newer version yet).
> 
> You mention that you use different security groups. Is the instance where the problem occurs allowed to access the instance where core-dns / kube-dns is running? If not, this would explain your resolve errors.

Yes, instances have access to send requests to each other. The sec-groups have been configured according to this guideline of the inbound and outbound traffic. https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html

I have scaled both kube-proxy and coredns to make sure there are instances of them on the affected nodegroup, and surely enough there is dns resolution inside the affected nodes now. I did not notice this at first but coredns always schedules on the first node that joins the cluster after the aws-auth-configmap.yaml is applied:

```
NAME                                                    READY   STATUS    RESTARTS   AGE   IP                NODE                             NOMINATED NODE
aws-node-8v6x4                                          1/1     Running   0          5m    192.168.150.94    ip-192-168-150-94.ec2.internal   <none>
aws-node-d6vjk                                          1/1     Running   0          5m    192.168.137.71    ip-192-168-137-71.ec2.internal   <none>
aws-node-hpplp                                          1/1     Running   0          5m    192.168.91.90     ip-192-168-91-90.ec2.internal    <none>
aws-node-sthxp                                          1/1     Running   0          5m    192.168.240.3     ip-192-168-240-3.ec2.internal    <none>
coredns-54bfbf84b7-6w98t                                1/1     Running   0          15m   192.168.232.65    ip-192-168-240-3.ec2.internal    <none>
coredns-54bfbf84b7-6z67z                                1/1     Running   0          15m   192.168.239.225   ip-192-168-240-3.ec2.internal    <none>
coredns-54bfbf84b7-8zspk                                1/1     Running   0          15m   192.168.198.40    ip-192-168-240-3.ec2.internal    <none>
coredns-54bfbf84b7-9lfsk                                1/1     Running   0          15m   192.168.255.139   ip-192-168-240-3.ec2.internal    <none>
coredns-54bfbf84b7-cqqgg                                1/1     Running   0          15m   192.168.203.3     ip-192-168-240-3.ec2.internal    <none>
coredns-54bfbf84b7-mlgh9                                1/1     Running   0          15m   192.168.200.253   ip-192-168-240-3.ec2.internal    <none>
coredns-54bfbf84b7-thhxg                                1/1     Running   0          15m   192.168.229.19    ip-192-168-240-3.ec2.internal    <none>

```

If this is the case and would be the problem, why isn't coredns deployed as daemonset on a fresh EKS cluster?

`sudo iptables -t nat -L` rules are the same (without major eye-shocking) differences between the nodes that have pod networking and the nodes that do not have pod networking.

**Comment by 0verc1ocker** [comment] 2019-02-25 03:44
Even when deployed as a daemonset dns resolution is still slow from the affected nodes:

On an affected node:
```
$ nslookup www.google.com
Server:    10.100.0.10
Address 1: 10.100.0.10 ip-10-100-0-10.ec2.internal

Name:      www.google.com
Address 1: 172.217.7.228 iad23s58-in-f4.1e100.net
```

On a normal node:

```
$ nslookup www.google.com
Server:    10.100.0.10
Address 1: 10.100.0.10 ip-10-100-0-10.ec2.internal

Name:      www.google.com
Address 1: 2607:f8b0:4004:802::2004 iad23s58-in-x04.1e100.net
Address 2: 172.217.7.228 iad23s58-in-f4.1e100.net
```

There seems to be an extra address when querying dns with nslookup within a node that works. Any ideas why this would be the case and why it would be slower on the tainted second nodegroup?

**Comment by 0verc1ocker** [comment] 2019-02-25 17:06
Anytime I go back to `602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:1.3.0` somehow the daemonset reverts back to `602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.3.2`. How is this handled and why is it happening @devkid ?

**Comment by 0verc1ocker** [comment] 2019-02-25 17:45
Alright, CNI is actually not the problem. Turns out to be a coredns version issue on EKS v1.11.

Final Solution: I followed some issues related to coredns and it led me to this issue here https://github.com/aws/containers-roadmap/issues/129 . I upgraded coredns image to version 1.3.1 and everything is working and dns resolution is fast again.

Please think about making cni version configurable and upgrading coredns version:

```
        image: coredns/coredns:1.3.1
```

I also needed to add rules for the sec-groups that were crearly not outlined in the sec-group configuration document. 

Allowing port 53 UDP and TCP in between all the nodegroups.

**Comment by devkid** [comment] 2019-02-25 17:51
Not sure how [aws/containers-roadmap#129](https://github.com/aws/containers-roadmap/issues/129) is related, it's about `Service`s of `type: ExternalName`, this doesn't have anything to do with resolving public DNS records. But if a new version of coredns fixed it, you probably got another bugfix that actually fixed your problem.

Regarding making CNI version configurable and upgrading coredns: neither of that is part of this repository and you can (and obviously already did, for the CNI) update both on your own and configure them to your liking.

**Comment by 0verc1ocker** [comment] 2019-02-25 17:56
@devkid , yes, it might have been another bug indeed, but updating the version definitely fixed it.

Also I was never able to get aws_node version to 1.3.0 on startup of the instances. It always reverted back to the image v1.3.2 , where is that being set. Is that somehow automatically set when applying node-auth-configmap via some bootstrap script on the ControlPlane?

**Comment by devkid** [comment] 2019-02-25 18:26
Not sure what you mean been by reverting back; didn't experience anything like that before. How are you applying your changes and verifying which version is running?

Regarding the actual titel of this issue: are you sure this about taints and networking at all? Newer version of coredns fixing your problem indicates otherwise.

**Comment by 0verc1ocker** [comment] 2019-02-25 20:09
> Not sure what you mean been by reverting back; didn't experience anything like that before. How are you applying your changes and verifying which version is running?

I am applying the image change on the daemonset with this command:

`kubectl edit daemonset -n kube-system aws-node`
and changing the image to 1.3.0

When I rebuild the nodegroups, I see that it has been changed back to v1.3.2 . 

> Regarding the actual titel of this issue: are you sure this about taints and networking at all? Newer version of coredns fixing your problem indicates otherwise.

Yes, I think the issue was all in coredns to start with.

**Comment by micahhausler** [comment] 2019-02-25 23:54
I launched a 1.11 EKS cluster with the taints you specified, and noticed that CoreDNS was unable to launch. 

The default tolerations on CoreDNS (v1.1.3) were:

```yaml
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
```

I updated the toleration on the CoreDNS deployment to 

```yaml
      tolerations:
      - operator: "Exists"
```
by running 
```bash
kubectl patch -n kube-system deployment/coredns --patch \
    '{"spec":{"template":{"spec":{"tolerations": [{"operator": "Exists"} ]}}}}'
```

I was able to get this all to work with CNI v1.3.2. Can you see if updating the tolerations on the CoreDNS deployment for v1.1.3 resolves the issue for you?

**Comment by 0verc1ocker** [comment] 2019-02-26 18:29
@micahhausler , Yes. I changed the tolerations on CoreDNS deployment when I converted it to a daemonset but it was still not working properly (intermittent DNS failures inside pods). Finally updating to v1.3.1 image of CoreDNS fixed the issues after that.

**Comment by izhukov** [comment] 2019-03-15 18:38
Also hit this issue. Changing toleration on coredns deployment did't help.
Pods on tainted nodes didn't resolve any names.

**Comment by discordianfish** [comment] 2019-04-17 14:34
Is it save to overwrite the tolerations of things that EKS deployed automatically? I'm worrying about some EKS update etc breaking/reverting it.

**Comment by 0verc1ocker** [comment] 2019-04-17 14:46
@discordianfish I'm not sure AWS has really ironed-out the upgrade paths for things like CoreDNS when using EKS. The version upgrade of components is still up to the user using EKS. They have a recommended versions for things like CoreDNS and the AMIs but I'm not sure upgrading versions on the EKS control plane will actually redeploy CoreDNS. At least it didn't for me in February. 

So given all this info, I think overwriting the tolerations should not break anything as it will still be up to you to manage the versioning of all such components.

**Comment by discordianfish** [comment] 2019-04-17 14:59
That would be alright with me, just haven't found a definitive answer on that. (Actually would even prefer if they didn't install it at all, that would make ownership clear).

**Comment by 0verc1ocker** [comment] 2019-04-17 18:50
Yeah, most of the time when upgrading EKS you would need to either upgrade the control plane or update the AMI so CoreDNS is initialized only in the beginning. KubeDNS and CoreDNS are interchangeable and configurable so far for EKS. [CoreDNS Guide](https://docs.aws.amazon.com/eks/latest/userguide/coredns.html)

The upgrade process should not interfere with this if those components are truly meant to be interchangeable.

**Comment by mateusvtt** [comment] 2019-07-10 03:39
I was facing DNS issues running more than one node group on EKS Cluster. My problem had nothing to do with taints flags, I was creating a new group using my own version of AWS provided CFN template (https://github.com/awslabs/amazon-eks-ami/blob/master/amazon-eks-nodegroup.yaml ). The issue here was that the core-dns was running only on the first node I had launched. When I launched the second node a new security-group was created:


```
NodeSecurityGroup:
    Type: AWS::EC2::SecurityGrou
    Properties:
      GroupDescription: Security group for all nodes in the cluster
      VpcId: !Ref VpcId
```

Thus only pods from the same node group could communicate with each other. Therefore was impossible to reach coredns on port 53 on another node group in another security group.

Workaround: Use same "NodeSecurityGroup" to all node groups. What I did was create this SG on EKS Cluster template and export it to NodeGroup template.

**Comment by whereisaaron** [comment] 2019-07-10 15:04
`eksctl` includes helpful functions to upgrade add-ons like CoreDNS during EKS upgrades.

https://eksctl.io/usage/cluster-upgrades/#updating-default-add-ons

> If you have upgraded from 1.10 to 1.11, you will need to replace kube-dns with coredns. To do that, run:
> `eksctl utils install-coredns`
> If you have upgraded from 1.11 to 1.12, run:
> `eksctl utils update-coredns`

**Comment by komljen** [comment] 2019-09-27 14:09
In my case, adding 53 UDP and TCP inbound rules in between all the node groups fixed the issue.

**Comment by mogren** [comment] 2019-09-27 19:46
1.11 issue: https://github.com/aws/amazon-vpc-cni-k8s/issues/328#issuecomment-467164715

**Closed by mogren** 2019-09-27 19:46 UTC

**Comment by npapapietro** [comment] 2021-06-23 15:47
I am experiencing this issue with 
EKS 1.20 
CNI image: amazon-k8s-cni:v1.7.5-eksbuild.1
coreDNS image: coredns:v1.8.3-eksbuild.1

**Comment by sermilrod** [comment] 2021-09-13 16:39
Same here, same issue with:
- EKS 1.21
- coreDNS image: coredns:v1.8.3-eksbuild.1\

I am using Fargate, but it is consistently reproducible with managed nodegroups too. Any solution for this?

**Comment by Cryptophobia** [comment] 2021-09-13 16:52
@sermilrod , force upgrade coreDNS or use the version AWS recommends for your Fargate control plane version?

https://docs.aws.amazon.com/eks/latest/userguide/coredns.html
