### ISSUE TITLE
Please consider to let bootstrap.sh supporting to use kubelet config file to set up kubelet parameters.

### ISSUE THREAD

**Issue by william-hou-ca** [awslabs/amazon-eks-ami#1354] opened 2023-07-17 13:47 UTC
**What would you like to be added**:
 As some parameters of kubelet are deprecated( like: --pod-infra-container-image, --max-pods, --container-log-max-files, --container-log-max-size) and when we configure them in a kubelet configure file and use --config to apply that kubelet configure file,  it causes kubelet only uses our customized kubeconfig file and ignore the kubeconfigure file created by bootstrap.sh. So worker nodes can not correctly run due to lack important kubelet parameters. Do we have any plan to migrate all parameters of kubelet to kubelet configuration file instead of the json file created by bootstrap.sh or support merging kubelet config file(pass by --config) with the json file?

**Why is this needed**:
Because some kubelet parameters are deprecated and k8s doc suggests to use kubelet config file to set up them instead of configuring them directly by kubelet parameters.

**Details of my test**:
1. set up configuration file in user-data of launch template.
~~~
cat<<'EOFFF' >/etc/kubernetes/kubelet/customUserData.conf
apiVersion: kubelet.config.k8s.io/v1beta1 
kind: KubeletConfiguration
containerLogMaxSize: "20Mi"
containerLogMaxFiles: 10
EOFFF

/etc/eks/bootstrap.sh my-cluster \
  --b64-cluster-ca <ca> \
  --apiserver-endpoint <> \
  --dns-cluster-ip <> \
  --container-runtime containerd \
  --kubelet-extra-args '--max-pods=20 --config /etc/kubernetes/kubelet/customUserData.conf' \
  --use-max-pods false
~~~

2. The node "ip-10-0-112-246.ec2.internal" is notReady, checking kube-proxy and aws-node, they reported no base image to run containers
~~~
[cloudshell-user@ip-10-4-81-122 ~]$ k get nodes
NAME                           STATUS     ROLES    AGE     VERSION
ip-10-0-111-226.ec2.internal   Ready      <none>   108m    v1.27.1-eks-2f008fe
ip-10-0-112-246.ec2.internal   NotReady   <none>   22m     v1.27.1-eks-2f008fe
ip-10-0-129-133.ec2.internal   Ready      <none>   7m16s   v1.27.1-eks-2f008fe
ip-10-0-148-251.ec2.internal   Ready      <none>   108m    v1.27.1-eks-2f008fe
ip-10-0-188-36.ec2.internal    Ready      <none>   108m    v1.27.1-eks-2f008fe
~~~

3. login into the ec2 and we can see there are 2 --config parameters
~~~
[root@ip-10-0-112-246 ~]# ps auxww| grep kubelet
root      3104  1.0  1.1 1659256 90548 ?       Ssl  14:45   0:14 /usr/bin/kubelet --config /etc/kubernetes/kubelet/kubelet-config.json --kubeconfig /var/lib/kubelet/kubeconfig --container-runtime-endpoint unix:///run/containerd/containerd.sock --image-credential-provider-config /etc/eks/image-credential-provider/config.json --image-credential-provider-bin-dir /etc/eks/image-credential-provider --node-ip=10.0.112.246--pod-infra-container-image=602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.5 --v=2 --hostname-override=ip-10-0-112-246.ec2.internal --cloud-provider=external --max-pods=20 --config /etc/kubernetes/kubelet/customUserData.conf
~~~

4. But kubelet only used the kubelet config file passed by --kubelet-extra-args and ignore the json file created by bootstrap.sh
~~~
[root@ip-10-0-112-246 ~]# journalctl -u kubelet | more
-- Logs begin at Fri 2023-07-14 14:45:05 UTC, end at Fri 2023-07-14 15:09:55 UTC. --
Jul 14 14:45:31 ip-10-0-112-246.ec2.internal systemd[1]: Starting Kubernetes Kubelet...
Jul 14 14:45:31 ip-10-0-112-246.ec2.internal systemd[1]: Started Kubernetes Kubelet.
Jul 14 14:45:31 ip-10-0-112-246.ec2.internal kubelet[3104]: Flag --container-runtime-end
...
Jul 14 14:45:31 ip-10-0-112-246.ec2.internal kubelet[3104]: I0714 14:45:31.620917    3104 flags.go:64] FLAG: --config="/etc/kubernetes/kubelet/customUserData.conf"
...
~~~

5. kubelet log reported errors:
~~~
...
Jul 14 14:45:34 ip-10-0-112-246.ec2.internal kubelet[3104]: I0714 14:45:34.359277    3104 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"run-dir\" (UniqueName:
\"[kubernetes.io/host-path/e0c2b284-ad8e-42af-a862-0c0987f77bc1-run-dir\ ](http://kubernetes.io/host-path/e0c2b284-ad8e-42af-a862-0c0987f77bc1-run-dir/)") pod \"aws-node-sk9fl\" (UID: \"e0c2b284-ad8e-42af-a862-0c0987f77bc1\") " pod="kube-system/aws-node-sk9fl"
Jul 14 14:45:34 ip-10-0-112-246.ec2.internal kubelet[3104]: I0714 14:45:34.359360    3104 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"xtables-lock\" (UniqueN
ame: \"[kubernetes.io/host-path/e0c2b284-ad8e-42af-a862-0c0987f77bc1-xtables-lock\ ](http://kubernetes.io/host-path/e0c2b284-ad8e-42af-a862-0c0987f77bc1-xtables-lock/)") pod \"aws-node-sk9fl\" (UID: \"e0c2b284-ad8e-42af-a862-0c0987f77bc1\") " pod="kube-system/aws-node-sk9fl"
Jul 14 14:45:34 ip-10-0-112-246.ec2.internal kubelet[3104]: I0714 14:45:34.359417    3104 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"xtables-lock\" (UniqueN
ame: \"[kubernetes.io/host-path/a0e838e2-5a33-4067-94a2-dc56f8643d7b-xtables-lock\ ](http://kubernetes.io/host-path/a0e838e2-5a33-4067-94a2-dc56f8643d7b-xtables-lock/)") pod \"kube-proxy-s2cqg\" (UID: \"a0e838e2-5a33-4067-94a2-dc56f8643d7b\") " pod="kube-system/kube-proxy-s2cqg"
Jul 14 14:45:34 ip-10-0-112-246.ec2.internal kubelet[3104]: I0714 14:45:34.359470    3104 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kubeconfig\" (UniqueNam
e: \"[kubernetes.io/configmap/a0e838e2-5a33-4067-94a2-dc56f8643d7b-kubeconfig\ ](http://kubernetes.io/configmap/a0e838e2-5a33-4067-94a2-dc56f8643d7b-kubeconfig/)") pod \"kube-proxy-s2cqg\" (UID: \"a0e838e2-5a33-4067-94a2-dc56f8643d7b\") " pod="kube-system/kube-proxy-s2cqg"
...
~~~

6. use kubelet parameters to set up those deprecated options, it still works. 
~~~
/etc/eks/bootstrap.sh my-cluster \
  --b64-cluster-ca <ca> \
  --apiserver-endpoint <> \
  --dns-cluster-ip <> \
  --container-runtime containerd \
  --kubelet-extra-args '--max-pods=20 --container-log-max-files=10 --container-log-max-size="5Mi" ' \
  --use-max-pods false
~~~

**Comment by cartermckinnon** [comment] 2023-07-17 21:17
I'm considering this a duplicate of #873, let me know if you disagree.

**Closed by cartermckinnon** 2023-07-17 21:17 UTC
