### ISSUE TITLE
Provide a valid way to apply taints to nodes at launch

### ISSUE THREAD

**Issue by jebbens** [awslabs/amazon-eks-ami#1138] opened 2022-12-21 21:51 UTC
**What would you like to be added**: A valid way to apply taints to nodes at launch

**Why is this needed**: According to the k8s [kubelet reference docs](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/), the `register-with-taints` argument has been deprecated and, therefore, should no longer be used in conjunction with `kubelet-extra-args`.

**Comment by cartermckinnon** [comment] 2022-12-22 22:47
While this flag is not yet scheduled for removal in a specific release, we need to decide on a way forward. I would consider this a duplicate of #873, let me know if you disagree @jebbens.

**Comment by jebbens** [comment] 2022-12-23 00:47
I don't think it's a duplicate b/c #873 prescribes a solution to address a broader capability, whereas this issue is specific to a single problem w/o concern for how it's solved. That said, I believe addressing #873 would solve this issue. It's clearly on your radar, which is the most important thing - I'll leave it up to you how to treat this ticket.

**Closed** 2024-10-21 18:31 UTC
