### ISSUE TITLE
Clock drift issues

### ISSUE THREAD

**Issue by ybstaked** [awslabs/amazon-eks-ami#1324] opened 2023-06-12 15:35 UTC
Our software has issues due to clock drifts between EC2 instances using this AMI.  We see it more in region: `ap-northeast-2`.

Relevant issues: 
* #249 
* #321

**Comment by cartermckinnon** [comment] 2023-06-15 22:54
I'm going to close this as a duplicate of #249 and keep looking into it there. Can you add details of how much drift you're observing?

**Closed by cartermckinnon** 2023-06-15 22:54 UTC
