### ISSUE TITLE
GRUB broken on gpu AMIs

### ISSUE THREAD

**Issue by rhino5oh** [awslabs/amazon-eks-ami#1454] opened 2023-10-05 18:36 UTC
On the latest version of the 1.27 EKS GPU node image, `amazon-eks-gpu-node-1.27-v20230919`, GRUB is broken. To reproduce this, simply spin up the AMI outside of a k8s cluster, and try to generate a grub config file by running:

 `sudo grub2-mkconfig -o /boot/grub2/grub.cfg`

This will fail with the following error: "/etc/default/grub: line 6: rd.driver.blacklist=nouveau: command not found"

If you try this in a previous version of the AMI, `amazon-eks-gpu-node-1.27-v20230816`, the command succeeds without error.

This is happening because of how the `GRUB_CMDLINE_LINUX` variable is being set in `/etc/default/grub`.

In the `amazon-eks-gpu-node-1.27-v20230919` AMI, the variable is set as follows:

`GRUB_CMDLINE_LINUX=nouveau.modeset=0 rd.driver.blacklist=nouveau`
**(Does NOT have quotes around the value. This is the root cause of the issue)**

In the older `amazon-eks-gpu-node-1.27-v20230816` AMI, the variable is being set as follows

`GRUB_CMDLINE_LINUX="nouveau.modeset=0 rd.driver.blacklist=nouveau"`
(This has quotes around the value)

**Comment by cartermckinnon** [comment] 2023-10-05 20:14
This is fixed in today’s AMI release. It’s caused by a bug in NVIDIA’s RPM spec that I fixed a while ago: https://github.com/NVIDIA/yum-packaging-nvidia-driver/pull/5

but it’s never trickled down to a release of the 470.x series driver packages. We had a hack for it that was unintentionally broken by some changes related to the 535.x series drivers.

Sorry for the hassle!

**Closed by cartermckinnon** 2023-10-05 20:14 UTC

**Comment by rhino5oh** [comment] 2023-10-06 12:52
Thanks for the insight @cartermckinnon . I verified that the issue is resolved in the `amazon-eks-gpu-node-1.27-v20231002` image
