### ISSUE TITLE
File descriptor limit change in AMI release `v20231220`

### ISSUE THREAD

**Issue by mmerkes** [awslabs/amazon-eks-ami#1551] opened 2023-12-22 14:54 UTC
**What happened**:
Customers are reporting hitting ulimits as a result of this PR #1535
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- AWS Region:
- Instance Type(s):
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):
- AMI Version:
- Kernel (e.g. `uname -a`):
- Release information (run `cat /etc/eks/release` on a node):

```
```

**Comment by johnkeates** [comment] 2023-12-22 15:15
We have hit this issue too, we have about ~1700 pods crashlooping in each cluster. I wonder if the CI doesn't test using a large enough workload?

**Comment by mmerkes** [comment] 2023-12-22 16:06
We have already reverted the change that caused this issue (#1535), we're rolling back the `v20231220` release and we're preparing to release new AMIs without the change ASAP. More guidance to come.

**Comment by maksim-paskal** [comment] 2023-12-22 16:16
It help us to restore our pods on new nodes, we using Karpenter

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
...
spec:
 ....
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash

    rm -rf /etc/systemd/system/containerd.service.d/20-limitnofile.conf

    --BOUNDARY--
```
and drain all new nodes from cluster

**Comment by jpedrobf** [comment] 2023-12-22 17:16
@mmerkes Can you please update us when the AMI is ready for usage?

**Comment by adwittumuluri** [comment] 2023-12-22 17:23
☝️ adding to that, an ETA would much appreciated as well. Is it in the magnitude of hours or days?

**Comment by atishpatel** [comment] 2023-12-22 17:35
I'm using this setup for now. Bumping soft limit from 1024 to 102400

Adding this to our bootstrap for now to 10x the soft limit.
```
- /usr/bin/sed -i 's/^LimitNOFILE.*$/LimitNOFILE=102400:524288/' /etc/systemd/system/containerd.service.d/20-limitnofile.conf
```

**Comment by cartermckinnon** [comment] 2023-12-22 17:46
This go runtime change in 1.19 automatically maxes-out the process’ NOFILE limit, so I would expect to see this problem with go binaries on earlier versions: https://github.com/golang/go/issues/46279

Has anyone run into this problem with a workload that isn’t a go program?

**Comment by mmerkes** [comment] 2023-12-22 17:59
> an ETA would much appreciated as well. Is it in the magnitude of hours or days?

We are working on releasing a new set of AMIs ASAP. I will post another update in 3-5 hours on the status. We should have a better idea then.

**Comment by 1lann** [comment] 2023-12-22 18:29
> Has anyone run into this problem with a workload that isn’t a go program?

People have mentioned running into this problem on envoy proxy, which is a C++ program.

**Comment by cartermckinnon** [comment] 2023-12-22 18:45
> People have mentioned running into this problem on envoy proxy

Yes, I've been looking into that. Envoy doesn't seem  to bump its own soft limit.

Other things I've noticed:
1. The soft limit of 1024 is the default on ECS: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Ulimit.html
2. Java's hotspot VM has maxed out the soft limit by default for ~20 years; point being there's wide variety in how the `no file` limit is handled: https://github.com/openjdk/jdk/blob/93fedc12db95d1e61c17537652cac3d4e27ddf2c/src/hotspot/os/linux/os_linux.cpp#L4575-L4589

**Comment by suket22** [comment] 2023-12-22 22:33
The EKS provided SSM Parameter to reference to the current EKS AMI has been reverted to reference the last good AMI in all regions globally. This will automatically resolve the issue for Karpenter and Managed node group users and any other systems that determine the latest EKS AMI from the SSM Parameter. 

We will provide another update by December 29 at 5:00 PM with a deployment timeline for new AMIs.

**Comment by polarathene** [comment] 2023-12-22 23:47
> We have already reverted the change that caused this issue

It'd be ideal to identify what software is not compatible and actually getting that addressed, but I understand the need to revert for the time being.

So long as you avoid `infinity`, most software will have minimal regression:
- `2^10 vs 2^20 slows some affected tasks by roughly 1,000x, as opposed to 2^30 where the delta is substantial.
- If software relies on the legacy [`select(2)` syscall](https://man7.org/linux/man-pages/man2/select.2.html) it expects the soft limit to be 1024 to correctly function (_additional [`select()` concerns documented here](https://github.com/envoyproxy/envoy/issues/31502#issue-2054539277) in a dedicated section_).
- For some software like Envoy, it can potentially exceed the traditional `2^20` hard limit. This has been reported on their GH issue tracker already. `infinity` would avoid that, but it would have been wiser for only Envoy to raise it's limit that high, than expect the environment to workaround Envoy needs, due to prior regression concern points.

If you need to set an explicit limit (_presumably because defaults are not sufficient_), and the advised `1024:524288` isn't enough due to software not requesting to raise it's limits... You could try matching the suggested hardlimit: `LimitNOFILE=524288`, or double that for the traditional hard limit (`2^20`).

That still won't be sufficient for some software as mentioned, but that is software that should know better and handle it's resource needs properly, exhausting the FD limit is per-process, so it's not necessarily an OOM event. The system-wide FD limit is much higher (_based on memory IIRC_).

---

> People have mentioned running into this problem on envoy proxy, which is a C++ program.

Envoy requires a large number of FDs, they have expressed that they're not interested in raising the soft limit internally and that admins should instead set a high enough soft limit.

I've since opened a feature request to justify why Envoy should raise the soft limit rather than defer that to be externally set high where it can negatively impact other software.

References:
- https://github.com/envoyproxy/envoy/issues/31502
- https://github.com/awslabs/amazon-eks-ami/pull/1535#issuecomment-1868076423

---

> 2\. Java's hotspot VM has bumped the limit by default for ~20 years;

https://github.com/systemd/systemd/blob/1742aae2aa8cd33897250d6fcfbe10928e43eb2f/NEWS#L60..L94

> _Note that there are also reports that using **very high hard limits** (e.g. 1G) is **problematic**:_
> _some software allocates large arrays with one element for each potential file descriptor (**Java**, …) — a high hard limit thus triggers **excessively large memory allocations** in these applications._

For `infinity`, this could require [1,000 - 1,000,000 times as much memory](https://github.com/containerd/containerd/issues/6707#issuecomment-1754114004) (_MySQL, not Java but an example of excessive memory allocation impact, coupled with [usual increased CPU load](https://github.com/orbstack/orbstack/issues/705)_), even though you may not need that much FDs, hence a poor default.

For Java, related to the systemd v240 release notes, there was [this github comment](https://github.com/systemd/systemd/issues/10921#issuecomment-442531877) at the time about Java's memory allocation. With the `524288` hard-limit that was 4MB, but `infinity` when resolving to `2^30` (many modern distros) would equate to 2,000x that (8GB).

While you cite 20 years, note that the hard-limit has incremented over time.
- That setting choice would have been a non-issue for most of that time, and a DIY workaround of overriding the hard-limit sweeps it under the rug 😅 
- The most substantial increase to the hard-limit was introduced with systemd v240 in 2018Q4 raising it to `2^30`.
- The systemd v240 release took a bit longer to arrive in downstreams of course. While some distros like Debian patched out the `2^30` hard-limit increase (_their actual motivation for this IIRC was actually due to a patched PAM issue that wasn't being resolved properly_).
- I haven't looked into the present state of JDK or MySQL to see if they still allocate excessively with a `2^30` hard-limit.

---

> point being there's wide variety in how the `nofile` limit is handled

This was all (_excludingEnvoy_) part of my [original research](https://github.com/containerd/containerd/pull/7566#issuecomment-1461142737) into moving the `LimitNOFILE=1024:524288` change forward. If you want a deep-dive resource on the topic for AWS, I have you covered! 😂 

Systemd has it right AFAIK, sane soft and hard limits. For AWS deployments some may need a higher hard limit, but it's a worry when software like Envoy doesn't document anything about that requirement and advises the stance of raising the soft limit externally.

**Comment by adjain131995** [comment] 2023-12-25 03:13
We were using karpenter which again is an AWS backed tool and it started picking up the new AMI dynamically as we started facing issues. 
As a hot fix we have harcoded the previous AMI
  amiSelector:
    aws::name: amazon-eks*node-1.25-v20231201
However, looking forward to the AMI fix we can make it dynamic again

**Comment by cartermckinnon** [comment] 2023-12-25 05:15
@adjain131995 Karpenter is awesome, but keep in mind that it’s beta software. Track issues like https://github.com/aws/karpenter-provider-aws/issues/5382 to make sure you have reasonable gates on your prod environments.

Can you provide more details about what broke for you? Setting standard file descriptor limits for containers is a change we have to make at some point in the future, so if there are fixes we can chase down in common projects, we need to file them 😊

**Comment by ndbaker1** [comment] 2023-12-26 22:31
As an update to the previous announcement, we are tracking for a new release by January 4th.

**Comment by Collin3** [comment] 2023-12-26 23:04
> As an update to the previous announcement, we are tracking for a new release by January 4th.
> 
> 

@ndbaker1 is this file descriptor limit change expected to be reintroduced to that release? Or will that still be excluded? Just wondering if we need to pin our AMI version until we implement our own fix for istio/envoy workloads or something is implemented in envoy itself to handle that change better

**Comment by cartermckinnon** [comment] 2023-12-27 00:59
@Collin3 that change has been reverted and will *not* be in the next AMI release 👍

**Comment by cartermckinnon** [comment] 2024-01-03 16:51
This is resolved in the latest release: https://github.com/awslabs/amazon-eks-ami/releases/tag/v20231230

**Closed by cartermckinnon** 2024-01-03 16:51 UTC
