### ISSUE TITLE
Error from server: error dialing backend: dial tcp 10.10.71.57:10250: i/o timeout

### ISSUE THREAD

**Issue by ShibraAmin18** [awslabs/amazon-eks-ami#1181] opened 2023-02-13 11:31 UTC
**What happened**:

for CIS ami changed /tmp to /home/ec2-user  and --bin-dir /bin/ to /usr/local/bin

[amazon-eks-ami/scripts/install-worker.sh](https://github.com/awslabs/amazon-eks-ami/blob/343e830dc4cbf0b2646026fced4cea7202a345a5/scripts/install-worker.sh#L138)

Line 138 in [343e830](https://github.com/awslabs/amazon-eks-ami/commit/343e830dc4cbf0b2646026fced4cea7202a345a5)

 sudo "${AWSCLI_DIR}/aws/install" --bin-dir /bin/ 
When using the image created with EKS node groups, cannot exec into or view pod logs.

Error from server: error dialing backend: dial tcp 10.10.71.57:10250: i/o timeout

**What you expected to happen**:
Successfully run the AMI created in EKS and be able to view logs and exec into the pod.

**Environment**:
- AWS Region: us-east-2
- Instance Type(s): t3a.medium
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.6"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): "1.23"
- AMI Version: CIS Amazon Linux 2 Benchmark v2.0.0.16 - Level 2-c41d38c4-3f6a-4434-9a86-06dd331d3f9c

**Comment by cartermckinnon** [comment] 2023-02-14 23:31
We need more information to understand the issue you're reporting. Does the node become `Ready`? Do the kubelet logs indicate any issues?

**Comment by cartermckinnon** [comment] 2023-05-25 07:16
I'm closing this issue because we don't have enough information to reach a conclusion.

**Closed by cartermckinnon** 2023-05-25 07:16 UTC

**Comment by raackley** [comment] 2023-06-29 19:28
Can this be reopened?  I believe I'm seeing the same problem, when building on top of the CIS Level 1 Benchmark AL2 AMI.

The AMI seems to build fine, but when deployed, I see issues similar to what was described, "i/o timeout", etc.  This only seems to happen for some pods, sometimes, when attempting to connect to the kubernetes API service endpoint IP that is local to the cluster.

I suspect the problem is from some certain sysctl parameter that was set in the CIS base image, but I can't find what exactly.

**Comment by cartermckinnon** [comment] 2023-06-30 20:31
@raackley we don't currently ship a CIS variant of the AMI, and this template doesn't explicitly support building on a CIS base. If there's a reasonable change we can make in the template to unblock that use case, we're not opposed; but we don't track CIS-specific issues here.

**Comment by raackley** [comment] 2023-06-30 21:17
@cartermckinnon  Sure, but is there a specific reason why it is known not to work?  Seems like it should be fine.  Obviously people are wanting this, so can this be a formal request for a CIS hardened base EKS image, or support to select a CIS hardened AMI to build your own?

**Comment by cartermckinnon** [comment] 2023-06-30 21:39
> Sure, but is there a specific reason why it is known not to work?

The issue you're describing:
>  This only seems to happen for some pods, sometimes, when attempting to connect to the kubernetes API service endpoint IP that is local to the cluster.

Sounds different from the one reported here. The OP was describing communication failures between the API server and kubelet.

> can this be a formal request for a CIS hardened base EKS image

This is a longstanding request (#99), it's absolutely on our radar.

> support to select a CIS hardened AMI to build your own?

If the issue lies in the CIS base AMI as you suspect, there's probably not much we can do in this template to ensure compatibility. If some logic here is causing the breakage, we're totally open to PR's.

**Comment by Th0masL** [comment] 2023-07-13 15:38
I'm also building CIS-hardened AMIs on Amazon Linux, and we were experiencing similar issues when upgrading from EKS 1.23 (on Docker) to EKS 1.25 (on Containerd).

On our side, the problem was due to the fact that the CIS-hardened AMI is disabling IP Fowarding, but Docker is able to re-enable it on the fly when the EC2 instance starts.

But ContainerD is not doing that, so IP Forwarding was disabled.

We added the following commands to the AMI build, and everything is working fine:

```
# Added this block under provisioners in the file eks-worker-al2.json
    {
      "type": "shell",
      "remote_folder": "{{ user `remote_folder`}}",
      "inline": "sudo bash {{ user `remote_folder`}}/scripts/enable_ip_forwarding.sh"
    },
```

And that's the content of the script

```
#!/bin/bash

# Script that enable IP Forwarding

# When using Docker, IP forwarding is automatically enabled by Docker.
# But when using ContainerD, we need to enabled manually.

sysctl -w net.ipv4.conf.default.forwarding=1
systcl -w net.ipv4.conf.all.forwarding=1
sysctl -w net.ipv4.conf.lo.forwarding=1
sysctl -w net.ipv4.ip_forward=1

# Get list of interfaces
list_interfaces=$( ifconfig | grep -E "^eth[0-9]:|^eni[0-9]:|^ens[0-9]:" | awk -F ':' '{print $1}' )

# Enable IP forwarding on all the interfaces found
for interface in $list_interfaces
do
    sysctl -w net.ipv4.conf.$interface.forwarding=1
done
```
