### ISSUE TITLE
Incorrect Max pods per node capacity.

### ISSUE THREAD

**Issue by romilpunetha** [awslabs/amazon-eks-ami#260] opened 2019-05-05 15:32 UTC
**What happened**:

According to . `https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt`, the max capacity of r5.large instance should be 29. However, when I launched the cluster with AWS recommended AMI `ami-09c3eb35bb3be46a4`, I see a different max capacity as reported by the k8s dashboard. 

**What you expected to happen**:

The scheduling of pods should stop after 29

**How to reproduce it (as minimally and precisely as possible)**:

Launch a eks cluster with the above mentioned ami and 2 r5.large instances. Keep adding pods.

**Anything else we need to know?**:

**Environment**:
- AWS Region: ap-south-1
- Instance Type(s): r5.large
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.1"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): "1.12"
- AMI Version: ami-09c3eb35bb3be46a4
- Kernel (e.g. `uname -a`): Darwin CF-LP00253.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-027c5e2ccf2970def"
BUILD_TIME="Fri Mar 29 20:07:35 UTC 2019"
BUILD_KERNEL="4.14.104-95.84.amzn2.x86_64"
ARCH="x86_64"

```

**Comment by mogren** [comment] 2020-03-11 17:27
@romil-punetha  Is this still an issue? The max-pods values look correct, and did work in my tests.

**Comment by galindro** [comment] 2020-07-28 12:02
@mogren This issue still persists. Let me explain to you what is going on in my environment. I launched a EKS cluster with managed node groups. Kubernetes version is `1.16` and Platform version is `eks.1`. This cluster has 5 nodegroups: 

  4 nodegroups uses t3a.medium instances
  1 is using g4dn.xlarge instances

According to https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt, both instance types (t3a.medium and g4dn.xlarge) can have only a maximum of 8 PODs per instance. But maximum pod limit set on each in the cluster is 17 and 29 respectively:

```bash
$ kubectl get nodes -o json |jq -r '(["NODE_NAME                                 ","INSTANCE_TYPE","AMI_ID              ","KUBELET_VERSION       ","MAX_PODS"] | (., map(length*"-"))), (.items[] | [.metadata.name, .metadata.labels."beta.kubernetes.io/instance-type", .metadata.labels."eks.amazonaws.com/nodegroup-image", .status.nodeInfo.kubeletVersion, .status.capacity.pods]) | @tsv'
NODE_NAME                                 	INSTANCE_TYPE	AMI_ID              	KUBELET_VERSION       	MAX_PODS
------------------------------------------	-------------	--------------------	----------------------	--------
ip-10-194-1-149.eu-west-1.compute.internal	g4dn.xlarge	ami-082231ade5abed30e	v1.16.13-eks-2ba888	29
ip-10-194-1-177.eu-west-1.compute.internal	g4dn.xlarge	ami-082231ade5abed30e	v1.16.13-eks-2ba888	29
ip-10-194-1-206.eu-west-1.compute.internal	t3a.medium	ami-0a3879f5c5e608624	v1.16.8-eks-e16311	17
ip-10-194-1-221.eu-west-1.compute.internal	t3a.medium	ami-0a3879f5c5e608624	v1.16.8-eks-e16311	17
ip-10-194-1-245.eu-west-1.compute.internal	g4dn.xlarge	ami-082231ade5abed30e	v1.16.13-eks-2ba888	29
ip-10-194-2-112.eu-west-1.compute.internal	g4dn.xlarge	ami-082231ade5abed30e	v1.16.13-eks-2ba888	29
ip-10-194-2-131.eu-west-1.compute.internal	g4dn.xlarge	ami-082231ade5abed30e	v1.16.13-eks-2ba888	29
ip-10-194-2-197.eu-west-1.compute.internal	t3a.medium	ami-0a3879f5c5e608624	v1.16.8-eks-e16311	17
ip-10-194-2-244.eu-west-1.compute.internal	t3a.medium	ami-0a3879f5c5e608624	v1.16.8-eks-e16311	17
ip-10-194-2-29.eu-west-1.compute.internal	g4dn.xlarge	ami-082231ade5abed30e	v1.16.13-eks-2ba888	29
ip-10-194-2-59.eu-west-1.compute.internal	g4dn.xlarge	ami-082231ade5abed30e	v1.16.13-eks-2ba888	29
ip-10-194-3-179.eu-west-1.compute.internal	g4dn.xlarge	ami-082231ade5abed30e	v1.16.13-eks-2ba888	29
ip-10-194-3-53.eu-west-1.compute.internal	g4dn.xlarge	ami-082231ade5abed30e	v1.16.13-eks-2ba888	29
ip-10-194-3-68.eu-west-1.compute.internal	t3a.medium	ami-0a3879f5c5e608624	v1.16.8-eks-e16311	17
ip-10-194-3-88.eu-west-1.compute.internal	g4dn.xlarge	ami-082231ade5abed30e	v1.16.13-eks-2ba888	29
ip-10-194-5-62.eu-west-1.compute.internal	t3a.medium	ami-0a3879f5c5e608624	v1.16.8-eks-e16311	17
ip-10-194-6-64.eu-west-1.compute.internal	t3a.medium	ami-0a3879f5c5e608624	v1.16.8-eks-e16311	17

```

**Comment by galindro** [comment] 2020-07-29 06:59
@mogren actually the mentioned list was wrong and caused a big confusion. Now the list represents the correct numbers after https://github.com/awslabs/amazon-eks-ami/pull/516 was merged. I think that this thread can be closed.

**Comment by mogren** [comment] 2020-07-29 12:45
Thanks @galindro, and sorry about the confusion caused by #510!

**Closed** 2020-07-29 12:46 UTC

**Comment by Pavanpatil0744** [comment] 2024-11-12 10:20
aws-eks-maximum-number-of-pods-per-ec2-node-instance-limi
https://medium.com/@techwithpatil/aws-eks-maximum-number-of-pods-per-ec2-node-instance-limit-a64527dcab77
